### ISSUE TITLE
no run 

### ISSUE THREAD

**Issue by l337quez** [NicholasKirchner/x49gp#5]
cc1: todos los avisos se tratan como errores
make[2]: *** [/home/ronal/Descargas/x49gp-master/qemu/qemu-git/rules.mak:18: tcg/tcg.o] Error 1
make[1]: *** [Makefile-small:69: subdir-arm-softmmu] Error 2
make[1]: se sale del directorio '/home/ronal/Descargas/x49gp-master/qemu/qemu-git'
make: *** [Makefile:264: qemu/qemu-git/arm-softmmu/fpu/softfloat.o] Error 2

**Comment by NicholasKirchner** [comment]
The best fork of this repo is at https://github.com/chwdt/x49gp .  Please go there.

**Comment by l337quez** [comment]
gracias por responder. voy a probar el otro que tu dices
